os: linux
dist: focal
language: java
jdk: openjdk17
cache:
  directories:
    - "$HOME/.m2"
branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: B8j40t3XBkCA3hruTtZH1AP1H2QhZFYKHrpvwpfo9cYihP4h6ynXeelyEhPbjao4flAnCtiNzUXq7/qAb7di1SPA+607Ip12EGxPwLGosoQlNEHY1js06mpzSqUh80cZDz1SAzJpvkGQjUHPUud2Namx4cQhdng++t5D5SlI7GZbqqC66/34UGI/qIy2CynNA2BFZRZ7u8HuU8wGenAGcXWP4aFZrVPc9Jr0hzSEYQTg5KizWdqiZ5aCEm8Z7ikJtyyTx2ILIJHOk0ybofwpo9X+gz0MxVhTR1F44WM/sducG2dfdFfstneVDP9qWuxdmV7k2d/YjwtLUlPLLmNxXWcsL/8qGP3vo5793o6+MA2yqSfriTm5ahOdgDiewQYZf/MtR6muRVj58WGITCCz4ITJQpg9ouZBgaae6spGC7yQkHfvy3AiVGXzrIJOav7g0e2ZZ0ctYqQHvqosy94JT1pSsTcwyzyAGsWz0CS9fECG4V4RAoWDP3owR5wyHFvbQjZHHRAeVrI4yfw/BGxVDnX+rhEbdRlEbhGTHkmgHuQDf2dGYvPVLEoYT6H73vL2HyAGFhzW0bqY2wNqBwXC9xn4rZ9vvpIS/nqdyBA7ZYNi9oHERf6YkhLfObSiobdtGzgyY+InsMH85DOL9//rWOwOVccruA8GGG2f0wA6YKc=
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=molgenis_vip-inheritance-matcher
deploy:
  provider: releases
  api_key:
    secure: EQdSh1+Z1iLrcCdtDNEdtiJ/klP5NdBZ42MPJywgM4nweAWmAestIPHji4Z1xdDQy7rF5zVLUMXXnFY8nPRTosG8vsh/sFT3RASNXHV0KnVAKkJML9UevcVeLsNSI96vXjx1uHtdZ1kWZFb4VeT3FaTLQlaI4X3UCTVJnlyRwIBjhBPxBs760SWWnvcF9sWDim9wwFAYp3KE57I4PqqqnVRf/GWE4f3hD4eYTd2S4xLsKxLSHor9CoAXFWJYBewdObMsm0VunicZLPIj3Mor8phqRbvOQsT2NCohDIB1rx6/bfnLs66ix7YnSuX6ZzJJNcszZtLvJPC938NmV1v+GLajwvVyxo163M1kCwPGx2N/o563M1ACsyzJ9RlqH8FUtHj3pk99oqy2pqxXo50GegWUIii3Ue6kF+sGWTqNPw4cXYAUfsercHlx07POw4iofzncYeyV7WaHGzrFyL32C/VuEd6YWYmCx+VwjGm/Qxj+uLfcH5/WtRjV/5AoeVciPmbd6ktOEJ1D1FDlaws/SEQQu6XdGxnzgNul1tHgXTKnJqb5HO4r9GUBLmAH1IpIiZCP4ZfqTB4A1/iFVuMKQDNhyBwrNfj3fIKOp7491dSNovI3l3qid39rfWPnJAbU2zq3m2uowJFToHx76zPGY1gb3xv9W1MP9nWU8NbHOtU=
  file: target/vcf-inheritance-matcher.jar
  prerelease: true
  on:
    tags: true
  edge: true # opt in to dpl v2
