os: linux
dist: jammy
language: java
jdk: openjdk17
cache:
  directories:
    - "$HOME/.m2"
branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: B8j40t3XBkCA3hruTtZH1AP1H2QhZFYKHrpvwpfo9cYihP4h6ynXeelyEhPbjao4flAnCtiNzUXq7/qAb7di1SPA+607Ip12EGxPwLGosoQlNEHY1js06mpzSqUh80cZDz1SAzJpvkGQjUHPUud2Namx4cQhdng++t5D5SlI7GZbqqC66/34UGI/qIy2CynNA2BFZRZ7u8HuU8wGenAGcXWP4aFZrVPc9Jr0hzSEYQTg5KizWdqiZ5aCEm8Z7ikJtyyTx2ILIJHOk0ybofwpo9X+gz0MxVhTR1F44WM/sducG2dfdFfstneVDP9qWuxdmV7k2d/YjwtLUlPLLmNxXWcsL/8qGP3vo5793o6+MA2yqSfriTm5ahOdgDiewQYZf/MtR6muRVj58WGITCCz4ITJQpg9ouZBgaae6spGC7yQkHfvy3AiVGXzrIJOav7g0e2ZZ0ctYqQHvqosy94JT1pSsTcwyzyAGsWz0CS9fECG4V4RAoWDP3owR5wyHFvbQjZHHRAeVrI4yfw/BGxVDnX+rhEbdRlEbhGTHkmgHuQDf2dGYvPVLEoYT6H73vL2HyAGFhzW0bqY2wNqBwXC9xn4rZ9vvpIS/nqdyBA7ZYNi9oHERf6YkhLfObSiobdtGzgyY+InsMH85DOL9//rWOwOVccruA8GGG2f0wA6YKc=
before_install:
  - cp travis.settings.xml $HOME/.m2/settings.xml
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=molgenis_vip-inheritance-matcher
before_deploy:
  - yes | gem update --system --force
  - gem install bundler
  - gem install uri
  - gem install logger
deploy:
  provider: releases
  api_key:
    secure: cDxqcprnUPh7FLmnRWv1A9eNhV17wfCzWxT8/mE80jVh8Z+UEyEUlh47/4wq2Qml5ivxtu/ty+4VMpL1h/0fhwCE0Tiec7tD9Xk4Wohy1gMrN6OiAMUXa1jxV4xetg2fY4lm0APJ5/BF4mLVtH9v31nnNvohUfxEocgY9mknd7pGfSZOGeGKjQpoQPpNaHB+prngE+2jBbTPHuN/nsrHQcbh496tv8QBMCQYDxGJVFt0mL7YEMNQuJS/E4mIYTJfuaVoN45FgN+nP61cBUL+dqh9fL4nmrPIuU/D5xggBPKxfBG1V3ePVaALXuhQs/Pp2LNISc8IPDIvK9tptS/FQcujM/Z0VtJEtNNMj+rtRiObLQn8/OyYKx3Nxv0tdxYR5oqftiuFwIOb2dmsOi3MFDtxtsOWe2b9Bqxb99BfP9c3ovGgEAvkPaTFIEv99xIfSVxY+xifF9uamu58I0x/wy+Y/iK9jPwG3JgZTyBD2yBjAnNZ5redsGbNDduAkt2uiyHprmWYHeVPLtqjStwjNcTz+qXFWtQ4Mfr29dF67Vf4BG4zjS+U8zMQk4GbkjPAcn56txk4JXuy+XchMd35Ti8YP10Df5qNuf/6pC0aQdfV3v4OnGXLUGgfg29kdMbPJXCkF1K/Rs/+6ODjj/Qczgo8tACH5YFGMQmB5zxoIRA=
  file: target/vcf-inheritance-matcher.jar
  prerelease: true
  on:
    tags: true
  edge: true # opt in to dpl v2
env:
  global:
    secure: HBaGhT8uZ+zt8aPqHkRkPk7mc80bzSwRHV+CbaT9d+Hc6j1snlENdqg3jrz6x1FAHbjnq50veeXkUxgVhVzfX+ip5hjxNzYZGiXv16ywtf0RQy8UGygTkRQtSKfwG9uVjnZ/YnpJhKWn7iuXxz2Rtpwix/Wwv8OyoHLUirq6/m9dpU0TUKG1yF605z/6U5Zyp/OhSY13iwRYW/AoScQCE2sDz7KYEpcknVbkyGy7w5w40EpVcetknu7MZlY3PZVpjpe19Ns+UIjxcAb12DlZ+W3V/tnO4XkQnBuZoe7TZRoMhgaaMETGsUv7g45rBjei/oQHX50/wxT+hv54jAo2rFAjFuHd+HsgT120vhcyifX2IHu22sC947vlj4cKqVElxU93Qx1Bb4Klx8TABNaPMrBPLIJ0yeNe/8DhWqIXtPGhDUSLC6pgMQc211iJwHKREtA3W2hgZJ8v1yUTja2vIhJRTjS9Ov4VCauqsN1XiV9iccbJw7oKQSHN8SmLuM9cYOcZ1RbM0xYuDSocgPpSba9Yakb/0d1TIjTx57vhn9GZylnuVEehPWAHCOBIz3hRxQ6Q8wBnIWj0yDewKZf8+QtLg7fAdpny9G7nWyQ09Cbg2QUJSzhv+S0Foj11dx9PM625TqxRtfm70B1pDCE7JRhbSp4FASMSF3AN4Vfzi3k=
